---
title: 2017 in the rearview mirror
author: John Johnson
date: '2018-01-01'
slug: 2017-in-the-rearview-mirror
draft: true
categories:
  - Greenville
tags:
  - reflection
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, fig.width=10)
```



Like many others, I've had an emotional rollercoaster of a year in 2017. Bob Rudis has published a [quantified self](https://rud.is/b/2017/12/29/2017-quantified-in-r/) kind of retrospection, but, alas, I haven't really participated in Stack Overflow, Twitter, or even blogging to do something similar. what I have done is peeked out of the pharma world enough to see trends in business, finance, and open data. And so that's where I begin 2018.

In the coming year, I see my interests evolving:

 * A stronger focus on collection and analysis of open and public data, with an emphasis on describing and predicting events that affect us on a local level (and I'll be using my own area of Upstate South Carolina as an example)
 * More widespread use of Bayesian statistics, especially as a way to combine inference from disparate data sources in a disciplined way
 * A focus on combining the hopeful accessibility of data science with the rigor of classical statistics to improve interpretability and reduce errors in reasoning
 * And new content twice a month
 
With that, I wish you a Happy 2018!
